services:
  db:
    image: postgres:15
    container_name: db_kunteynir
    restart: unless-stopped
    environment:
      POSTGRES_DB: helper_bot_db
      POSTGRES_USER: maesim
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: helperbot:latest
    container_name: helper_bot_kunteynir
    depends_on:
      - db
    env_file: 
      - .env
    volumes:
      - ./migrations:/app/migrations
    command: ["/app/bot"]

volumes:
  postgres_data: